const LOADINGSTART='LOADING_START';
const LOADINGEND='LOADING_END';
const SEARCH='SEARCH_RULET_LIST_DATA';
const SETFORMITEMS = 'SET_FORM_ITEMS';
const SET_DATAS = 'SET_DATAS';
const SET_SEARCH_OBJ = 'SET_SEARCH_OBJ';
const SET_PARENT_LIST = 'SET_PARENT_LIST';
const SET_All_LIST = 'SET_All_LIST';
const SET_UNIQUE = 'SET_UNIQUE';
const BTN_LOADING_ACTIVE = 'BTN_LOADING_ACTIVE';
const BTN_LOADING_DISPLAY = 'BTN_LOADING_DISPLAY';
const BTN_REQUEST_ACTIVE = 'BTN_REQUEST_ACTIVE';
const BTN_REQUEST_DISPLAY = 'BTN_REQUEST_DISPLAY';
const ON_EXPAND_KEY = 'ON_EXPAND_KEY';
export default {
    LOADINGSTART,
    LOADINGEND,
    SEARCH,
    SETFORMITEMS,
    SET_DATAS,
    SET_SEARCH_OBJ,
    SET_PARENT_LIST,
    SET_All_LIST,
    SET_UNIQUE,
    BTN_LOADING_ACTIVE,
    BTN_LOADING_DISPLAY,
    BTN_REQUEST_ACTIVE,
    BTN_REQUEST_DISPLAY,
    ON_EXPAND_KEY,
}