const LOADINGSTART='LOADING_START';
const LOADINGEND='LOADING_END';
const SEARCH='SEARCH_RULET_LIST_DATA';
const QUERYJOBTITLE = 'QUERY_JOB_TITLE';
const GETFORMITEMS = 'GET_FORM_ITEMS';
const SET_DATAS = 'SET_DATAS';
const setSearchObj = 'setSearchObj';
const ORG_TREE_DATAS = 'ORG_TREE_DATAS';
const ORG_TREE_CHECKED = 'ORG_TREE_CHECKED';
const ORG_FORM_ITEMS = 'ORG_FORM_ITEMS';
const SHOW_ROLE_EDIT = 'SHOW_ROLE_EDIT';
const SET_ROLE_LIST = 'SET_ROLE_LIST';
const SET_USER_ROLE_LIST = 'SET_USER_ROLE_LIST';
const SET_USER = 'SET_USER';
const SET_BTN_LOADING_ACTIVE = 'SET_BTN_LOADING_ACTIVE';
const SET_BTN_DLOADING_DISPLAY = 'SET_BTN_DLOADING_DISPLAY';
const BTN_REQUEST_ACTIVE = 'BTN_REQUEST_ACTIVE';
const BTN_REQUEST_DISPLAY = 'BTN_REQUEST_DISPLAY';
const USER_RESOURCE = 'USER_RESOURCE';
const ON_EXPAND_KEY = 'ON_EXPAND_KEY';

export default {
    LOADINGSTART,
    LOADINGEND,
    SEARCH,
    QUERYJOBTITLE,
    GETFORMITEMS,
    SET_DATAS,
    setSearchObj,
    ORG_TREE_DATAS,
    ORG_TREE_CHECKED,
    ORG_FORM_ITEMS,
    SHOW_ROLE_EDIT,
    SET_ROLE_LIST,
    SET_USER_ROLE_LIST,
    SET_USER,
    SET_BTN_LOADING_ACTIVE,
    SET_BTN_DLOADING_DISPLAY,
    BTN_REQUEST_ACTIVE,
    BTN_REQUEST_DISPLAY,
    USER_RESOURCE,
    ON_EXPAND_KEY,
}