import {createAction} from "redux-actions";

const LOADINGSTART='LOADING_START';
const LOADINGEND='LOADING_END';
const SEARCH='SEARCH_RULET_LIST_DATA';
const QUERYROLETYPE = 'QUERY_ROLE_TYPE';
const GETFORMITEMS = 'GET_FORM_ITEMS';
const SEARCHMODULE = 'SEARCH_MODULE';
const SEARCHMODULECHECKED = 'SEARCH_MODULE_CHECKED';
const setDatas = 'setDatas';
const setSearchObj = 'setSearchObj';
const setResourceDatas = 'setResourceDatas';
const SET_BTN_LOADING_ACTIVE = 'SET_BTN_LOADING_ACTIVE';
const SET_BTN_DLOADING_DISPLAY = 'SET_BTN_DLOADING_DISPLAY';
const BTN_REQUEST_ACTIVE = 'BTN_REQUEST_ACTIVE';
const BTN_REQUEST_DISPLAY = 'BTN_REQUEST_DISPLAY';
const USER_RESOURCE = 'USER_RESOURCE';
const LOADING_START_R = 'LOADING_START_R';
const LOADING_END_R = 'LOADING_END_R';
export default {
    LOADINGSTART,
    LOADINGEND,
    SEARCH,
    QUERYROLETYPE,
    GETFORMITEMS,
    SEARCHMODULE,
    SEARCHMODULECHECKED,
    setDatas,
    setSearchObj,
    setResourceDatas,
    SET_BTN_LOADING_ACTIVE,
    SET_BTN_DLOADING_DISPLAY,
    BTN_REQUEST_ACTIVE,
    BTN_REQUEST_DISPLAY,
    USER_RESOURCE,
    LOADING_START_R,
    LOADING_END_R,
}